FROM boinc/client:latest

LABEL maintainer="BOINC" \
      description="A base container image for lightweight AMD OpenCL-savvy BOINC clients"

RUN apt-get update && apt-get install -y --no-install-recommends \
    # Generic OpenCL ICD Loader
    ocl-icd-libopencl1 \
    # OpenCL Driver for AMD GPUs
    mesa-opencl-icd && \
    rm -rf /var/lib/apt/lists/*

