FROM boinc/client:opencl

LABEL maintainer="BOINC" \
      description="A base container image for lightweight Intel GPU-savvy BOINC clients"

RUN apt-get update && apt-get install -y \
       libgl1-mesa-glx \
       libgl1-mesa-dri \
       beignet-opencl-icd \
    && rm -rf /var/lib/apt/lists/*
