FROM boinc/client:latest

LABEL maintainer="BOINC" \
      description="A base container image for lightweight NVIDIA CUDA-savvy BOINC clients"

RUN echo "deb http://deb.debian.org/debian stretch contrib non-free" >> /etc/apt/sources.list \
    && apt-get update && apt-get install -y --no-install-recommends \
        boinc-client-nvidia-cuda \
    && rm -rf /var/lib/apt/lists/*
