FROM boinc/client:latest

LABEL maintainer="BOINC" \
      description="A base container image for lightweight Intel GPU-savvy BOINC clients"

RUN apt-get update && apt-get install -y --no-install-recommends \
       libgl1-mesa-glx \
       libgl1-mesa-dri \
    && rm -rf /var/lib/apt/lists/*
