FROM boinc/client:latest

LABEL maintainer="BOINC" \
      description="A base container image for lightweight VirtualBox-savvy BOINC clients"

# Install
RUN apt-get update && apt-get install -y --no-install-recommends \
# Install VirtualBox
    virtualbox && \
# Cleaning up
    rm -rf /var/lib/apt/lists/*
