FROM arm32v7/alpine:edge

LABEL maintainer="BOINC" \
      description="A lightweight BOINC client on ARMv7 32-bit architecture."

# Global environment settings
ENV BOINC_GUI_RPC_PASSWORD="123" \
    BOINC_REMOTE_HOST="127.0.0.1" \
    BOINC_CMD_LINE_OPTIONS=""

# Copy files
COPY bin/ /usr/bin/

# Configure
WORKDIR /var/lib/boinc

# BOINC RPC port
EXPOSE 31416

# Install
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    boinc

CMD ["start-boinc.sh"]
