#!/bin/bash

#
# This file is necessary to ensure that the Docker Cloud autobuild builds the
# base Dockerfile first, then the extended versions (like `intel`
# or `nvidia`) since those depend on the base one. 
#

# Base image
docker build -t boinc/client:latest .

# Nvidia image. Multi GPU container depends on it.
docker build -t boinc/client:nvidia -f Dockerfile.nvidia .

docker build -t $IMAGE_NAME -f $DOCKERFILE_PATH .
